bugtracker/bugtracker/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('projects.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-new/', user_views.new_password, name='password-new'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password-reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password-reset-done'),
    path('password-reset-confirm', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password-reset-confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password-reset-complete'),
    path('profile/', user_views.profile, name='profile'),
    path('status/', include('status.urls')),
    path('register/', user_views.register, name='register'),
    path('projects/', include('projects.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bugtracker/projects/urls.py
from django.urls import path
from . import views
from .views import BugListView, BugCreateView, BugDetailView, BugUpdateView, BugProjectListView, BugDeleteView, CommentCreateView, CommentDeleteView

urlpatterns = [
    path('', views.home, name="projects-home"),
    path('bugs/', BugListView.as_view(), name="bugs-list"),
    path('bugs/create/', BugCreateView.as_view(), name="bugs-create"),
    path('bugs/create/comment/<int:id>', CommentCreateView.as_view(), name="bugs-create-comment"),
    path('bugs/detail/<int:pk>', BugDetailView.as_view(), name="bugs-detail"),
    path('bugs/update/<int:pk>', BugUpdateView.as_view(), name="bugs-update"),
    path('bugs/delete/<int:pk>', BugDeleteView.as_view(), name="bugs-delete"),
    path('bugs/delete/comment/<int:pk>', CommentDeleteView.as_view(), name="comment-delete"),
    path('bugs/project/<int:id>/<str:name>', BugProjectListView.as_view(), name="bugs-project"),
    path('search-results/', views.search_results, name="search-results")
]

bugtracker/status/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="status-home"),
    path('contactadmin/', views.ContactFormView.as_view(), name="contact-admin")
]

bugtracker/projects/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Project(models.Model):
    name = models.CharField(max_length=50)
    PROJ_TYPES = (
        ('D', 'Dev'),
        ('P', 'Print'),
        ('O', 'Other'),
    )
    proj_type = models.CharField(max_length=1, choices=PROJ_TYPES)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    editors = models.ManyToManyField(User)

    def __str__(self):
        return self.name

class Bug(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=2000, help_text="2000 character limit.")
    BUG_TYPES = (
        ('V', 'Visual'),
        ('L', 'Logical'),
        ('O', 'Other'),
    )
    bug_type = models.CharField(max_length=1, choices=BUG_TYPES)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    image = models.ImageField(upload_to='bug_pics', default='default_bug.png') #image field has automatic validation to ensure the upload is a valid image - no need for further validation on file size since we are using Pillow to resize to a manageable size
    image2 = models.ImageField(upload_to='bug_pics', default='default_bug.png')

    resolved = models.BooleanField(default=False)

    def __str__(self):
        return f'Bug ID: {self.id}'
    
    def get_absolute_url(self):
        return reverse('bugs-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-date_added']

class Comment(models.Model):
    desc = models.CharField(max_length=1000, help_text="1000 character limit.")
    date_added = models.DateTimeField(auto_now_add=True)
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    image = models.ImageField(upload_to='bug_pics', default='default_bug.png')

    def get_absolute_url(self):
        return reverse('bugs-detail', kwargs={'pk': self.bug.pk})

    class Meta:
        ordering = ['-date_added']
    
    def __str__(self):
        return f'Comment ID: {self.id}'

bugtracker/projects/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project, Bug, Comment
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django import forms
from django.core.paginator import Paginator
from django.views.decorators.http import require_GET
from django.http import HttpResponse, Http404

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

# Create your views here.
@login_required
def home(request):
    projects = Project.objects.filter(editors=request.user)
    # if this is converted to a class-based view, the user can be accessed with self.request.user and used for queryset filtering
    #bugs = projects.first().bug_set.all() #how do I filter this on a per project basis, right now it just returns bugs for the first project

    context = {
        'projects': projects,
        'title': 'Projects'
    }
    
    return render(request, 'projects/home.html', context)

@require_GET
def search_results(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        bugs = Bug.objects.filter(desc__icontains=q)
        return render(request, 'projects/search_results.html', {'bugs': bugs, 'query': q})
    else:
        raise Http404("Invalid Search")

class BugListView(LoginRequiredMixin, ListView):
    model = Bug
    context_object_name = "bug_list"
    ordering = ['-date_added']
    paginate_by = 5

class BugProjectListView(LoginRequiredMixin, ListView):
    model = Bug
    paginate_by = 5

    template_name="projects/project_bugs.html"

    def get_queryset(self):
        project = get_object_or_404(Project, id=self.kwargs.get('id')) # can also just do self.kwargs['id'] here. Standard Python dict retrieval.
        return Bug.objects.filter(project=project)

class BugDetailView(LoginRequiredMixin, DetailView):
    model = Bug

    # overriding get_object here allows you to apply extra functionality, such as modifying a "last_accessed" value on the db object before returning it to the user
    # https://docs.djangoproject.com/en/3.1/topics/class-based-views/generic-display/#performing-extra-work




############
## CREATE ##
############
class BugCreateSupportForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = ['name', 'desc', 'image', 'image2', 'bug_type', 'project']
        widgets = {
            'desc': forms.Textarea
        }

class BugCreateView(LoginRequiredMixin, CreateView):
    form_class = BugCreateSupportForm # form_class allows you to use forms.ModelForm and utilize functionality like widgets
    model = Bug

    def form_valid(self, form):
        logger.error("new bug created")
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentCreateSupportForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['desc', 'image']
        widgets = {
            'desc': forms.Textarea
        }

class CommentCreateView(LoginRequiredMixin, CreateView):
    form_class = CommentCreateSupportForm
    template_name = 'projects/comment_form.html'

    def form_valid(self, form):
        bug = get_object_or_404(Bug, id=self.kwargs.get('id'))
        form.instance.bug = bug
        form.instance.author = self.request.user
        return super().form_valid(form)
############
############





############
## UPDATE ##
############
class BugUpdateSupportForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = ['name', 'desc', 'image', 'image2', 'bug_type', 'resolved']
        widgets = {
            'desc': forms.Textarea
        }

class BugUpdateView(LoginRequiredMixin, UpdateView):
    form_class = BugUpdateSupportForm 
    model = Bug

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
############
############




############
## DELETE ##
############
class BugDeleteView(LoginRequiredMixin, DeleteView):
    model = Bug
    success_url = reverse_lazy('bugs-list')


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    success_url = reverse_lazy('bugs-list')
############
############

bugtracker/projects/templates/projects/bug_confirm_delete.html
{% extends "status/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Confirm Delete
                </legend>
                {{ form|crispy }}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Confirm</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

bugtracker/projects/templates/projects/bug_detail.html
{% extends "status/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
            <small class="text-muted"><strong>Project:</strong> <a href="{% url 'bugs-project' bug.project.id bug.project.name %}">{{ bug.project }}</a> | <strong>Author:</strong> {{ bug.author }}<br/></small>
            <small class="text-muted">Date Created: {{ bug.date_added }}</small>
            <small class="text-muted">Last Modified: {{ bug.date_modified }}</small>
            </div>
            <h2>{{ bug.name|title }}</h2>
            <p>{{bug.desc}}</p>
                <img class="bug_image" src="{{ bug.image.url }}">
            {% if bug.image2.url != '/media/default_bug.png' %}
                <br/><img class="bug_image" src="{{ bug.image2.url }}">
            {% endif %}
            <p class="article-content"><strong>Bug Type:</strong> {{ bug.get_bug_type_display }}</p>
            <p><strong>Status:</strong> {{bug.resolved|yesno:"<span style='color: white; background-color: green; padding: 5px;'>Resolved</span>, <span style='color: white; background-color: red; padding: 5px;'>Unresolved</span>"|safe}}</p>
            <a class="btn btn-outline-primary btn-sm dark-button" href="{% url 'bugs-update' bug.id %}"><i class="far fa-edit"></i> Edit</a>
            <a class="btn btn-danger btn-sm" href="{% url 'bugs-delete' bug.id %}"><i class="far fa-trash-alt"></i> Delete</a>
        </div>
        
    </article>
    <article class="media content-section">
        <div class="media-body">
                <div style="display: flex; justify-content: space-between; padding: 5px;">
                    <h4>Comments</h4>
                    <div><a class="btn btn-outline-primary btn-sm" href="{% url 'bugs-create-comment' bug.id %}"><i class="fas fa-plus"></i> Add New Comment</a></div>
                </div>
                {% for comment in bug.comment_set.all %}
                    <div class="article-metadata-comments">
                        <small class="text-muted"><strong>Author:</strong> {{ comment.author }}<br>
                        Date Created:</strong> {{ comment.date_added }}</small>
                        <p>{{comment.desc}}</p>
                        {% if request.user == comment.author %}
                        <a class="btn btn-danger btn-sm" href="{% url 'comment-delete' comment.id %}"><i class="far fa-trash-alt"></i> Delete</a>
                        {% endif %}
                    </div>
                {% endfor %}
            </ul>
        </div>
    </article>

    
{% endblock content %}

bugtracker/projects/templates/projects/bug_form.html
{% extends "status/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Create New Bug
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Submit</button>
            </div>
        </form>
    </div>
    
{% endblock content %}

bugtracker/projects/templates/projects/bug_list.html
{% extends "status/base.html" %}
{% block content %}
    <h1>Bugs</h1>
    {% include 'projects/pagination.html' %}
        
    {% for bug in bug_list %} 
    {# overriding context_object_name allows you to specify a name of the list of objects (i.e. bug_list) instead of the default "object_list" #}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted"><strong>Project:</strong> <a href="{% url 'bugs-project' bug.project.id bug.project.name %}">{{ bug.project }}</a> | <strong>Created by:</strong> {{ bug.author }}<br/></small>
                    <small class="text-muted">Date Created: {{ bug.date_added }}</small>
                    <small class="text-muted">Last Modified: {{ bug.date_modified }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'bugs-detail' bug.id %}">{{ bug.name|title }}</a></h2>
                <p>{{bug.desc|truncatewords:"10"}}</p>
                <p class="article-content"><strong>Bug Type:</strong> {{ bug.get_bug_type_display }}</p>
                <p><strong>Status:</strong> {{bug.resolved|yesno:"<span style='color: white; background-color: green; padding: 5px;'>Resolved</span>, <span style='color: white; background-color: red; padding: 5px;'>Unresolved</span>"|safe}}</p>
                <a class="btn btn-primary btn-sm dark-button" href="{% url 'bugs-detail' bug.id %}"><i class="far fa-file-alt"></i> View Full Details</a> 
                <a class="btn btn-primary btn-sm dark-button" href="{% url 'bugs-update' bug.id %}"><i class="far fa-edit"></i> Edit</a>
                <a class="btn btn-danger btn-sm" href="{% url 'bugs-delete' bug.id %}"><i class="far fa-trash-alt"></i> Delete</a>
            </div>
        </article>
    {% endfor %}

    {% include 'projects/pagination.html' %}
    
{% endblock content %}

bugtracker/projects/templates/projects/comment_form.html
{% extends "status/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Create New Comment for Bug ID: {{ view.kwargs.id }}
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Submit</button>
            </div>
        </form>
    </div>
    
{% endblock content %}

bugtracker/projects/templates/projects/home.html
{% extends "status/base.html" %}
{% block content %}
    {% for project in projects %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                        <div>
                            <small class="text-muted"><strong>Date Created:</strong> {{ project.date_added }}</small>
                            <small class="text-muted"><strong>Last Modified:</strong> {{ project.date_modified }}</small>
                        </div>
                </div>
                <h2><a class="article-title" href="{% url 'bugs-project' project.id project.name %}">{{ project.name }}</a></h2>
                <p class="article-content"><strong>Project Type:</strong> {{ project.get_proj_type_display }}</p>
                <p class="article-content"><strong>Number of bugs:</strong> {{ project.bug_set.count }}</p>
                <p><strong>Recent bugs: </strong>
                    <ul class="bugs">
                        {% for bug in project.bug_set.all|slice:":3" %}
                        <li><a href="{% url 'bugs-detail' bug.id %}">Bug ID: {{bug.id}} | {{ bug.name }} - {{ bug.desc|truncatewords:"5"}}</a></li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
        </article>
    {% endfor %}
    
{% endblock content %}

bugtracker/projects/templates/projects/pagination.html
    {% if is_paginated %}
    <div class="container" style="display: flex; justify-content: center;">
        {% if page_obj.has_previous %}
            <a class="btn btn-light btn-sm mb-4" href="?page=1"><i class="fas fa-angle-double-left"></i> First</a>
            <a class="btn btn-light btn-sm mb-4" href="?page={{page_obj.previous_page_number}}"><i class="fas fa-angle-left"></i> Previous</a>
        {% else %}
            <a class="btn btn-light btn-sm mb-4 disabled" href="#" role="button" aria-disabled="true"><i class="fas fa-angle-double-left"></i> First</a>
            <a class="btn btn-light btn-sm mb-4 disabled" href="#" role="button" aria-disabled="true"><i class="fas fa-angle-left"></i> Previous</a>
        {% endif %}
        <div style="padding: 4px 20px 20px 20px;">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</div>
        {% if page_obj.has_next %}
            <a class="btn btn-light btn-sm mb-4" href="?page={{page_obj.next_page_number}}">Next <i class="fas fa-angle-right"></i></a>
            <a class="btn btn-light btn-sm mb-4" href="?page={{page_obj.paginator.num_pages}}">Last <i class="fas fa-angle-double-right"></i></a>
        {% else %}
            <a class="btn btn-light btn-sm mb-4 disabled" href="#" role="button" aria-disabled="true">Next <i class="fas fa-angle-right"></i></a>
            <a class="btn btn-light btn-sm mb-4 disabled" href="#" role="button" aria-disabled="true">Last <i class="fas fa-angle-double-right"></i></a>
        {% endif %}
    </div>
    {% endif %}

bugtracker/projects/templates/projects/project_bugs.html
{% extends "status/base.html" %}
{% block content %}
    <h1>Bugs</h1>
    <h4><strong>Project ID:</strong> {{ view.kwargs.id }} | <strong>Project Name:</strong> {{view.kwargs.name}} | <strong>Total bugs:</strong> {{ page_obj.paginator.count }}</h4>
    {% include 'projects/pagination.html' %}

    {% for bug in object_list %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <div style="display: flex; justify-content: space-between;">
                        <div>
                            <small class="text-muted"><strong>Author:</strong> {{ bug.author }}</small>
                        </div>
                        <div>
                            <small class="text-muted"><strong>Date Created:</strong> {{ bug.date_added }}</small>
                            <small class="text-muted"><strong>Last Modified:</strong> {{ bug.date_modified }}</small>
                        </div>
                    </div>
                </div>
                <h2><a class="article-title" href="{% url 'bugs-detail' bug.id %}">{{ bug.name|title }}</a></h2>
                <p>{{bug.desc}}</p>
                <p class="article-content"><strong>Bug Type:</strong> {{ bug.get_bug_type_display }}</p>
                <p><strong>Status:</strong> {{bug.resolved|yesno:"<span style='color: white; background-color: green; padding: 5px;'>Resolved</span>, <span style='color: white; background-color: red; padding: 5px;'>Unresolved</span>"|safe}}</p>
                <a class="btn btn-primary btn-sm dark-button" href="{% url 'bugs-detail' bug.id %}"><i class="far fa-file-alt"></i> View Full Details</a> 
                <a class="btn btn-primary btn-sm dark-button" href="{% url 'bugs-update' bug.id %}"><i class="far fa-edit"></i> Edit</a>
                <a class="btn btn-danger btn-sm" href="{% url 'bugs-delete' bug.id %}"><i class="far fa-trash-alt"></i> Delete</a>
            </div>
        </article>
    {% endfor %}

    {% include 'projects/pagination.html' %}
    
{% endblock content %}

bugtracker/projects/templates/projects/search_results.html
{% extends "status/base.html" %}
{% block content %}
    <h1>Search Results For: {{ query }}</h1>
    {% if bugs %}
    <p>Found {{ bugs|length }} bug{{ bugs|pluralize }}.</p>
        {% for bug in bugs %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <small class="text-muted">Project: <a href="{% url 'bugs-project' bug.project.id %}">{{ bug.project }}</a> | Author: {{ bug.author }}<br/></small>
                        <small class="text-muted">Date Created: {{ bug.date_added }}</small>
                        <small class="text-muted">Last Modified: {{ bug.date_modified }}</small>
                    </div>
                    <h2><a class="article-title" href="{% url 'bugs-detail' bug.id %}">{{ bug.name|title }}</a></h2>
                    <p>{{bug.desc}}</p>
                    <p class="article-content">Bug Type: {{ bug.get_bug_type_display }}</p>
                    <p>Status: {{bug.resolved|yesno:"<span style='font-weight: bold; color: white; background-color: green; padding: 5px;'>Resolved</span>, <span style='font-weight: bold; color: white; background-color: red; padding: 5px;'>Open</span>"|safe}}</p>
                    <a class="btn btn-outline-primary btn-sm" href="{% url 'bugs-detail' bug.id %}"><i class="far fa-file-alt"></i> View Full Details</a> 
                    <a class="btn btn-outline-primary btn-sm" href="{% url 'bugs-update' bug.id %}"><i class="far fa-edit"></i> Edit</a>
                    <a class="btn btn-outline-danger btn-sm" href="{% url 'bugs-delete' bug.id %}"><i class="far fa-trash-alt"></i> Delete</a>
                </div>
            </article>    
        {% endfor %}
    {% else %}
        <p>No bugs matched your search criteria.</p>
    {% endif %}
{% endblock content %}